# fly.toml file generated for javalinstagram on 2022-08-26T14:53:13+01:00

app = "javalinstagram"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[build]
  builder = "heroku/buildpacks:18"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

#[deploy]
#  release_command = "java -cp target/javalinstagram-1.0-SNAPSHOT-jar-with-dependencies.jar javalinstagram.util.DbSetupUtilKt"

[processes]
  web = "java -jar target/javalinstagram-1.0-SNAPSHOT-jar-with-dependencies.jar"
#  web = "java -cp target/javalinstagram-1.0-SNAPSHOT-jar-with-dependencies.jar javalinstagram.util.DbSetupUtilKt && java -jar target/javalinstagram-1.0-SNAPSHOT-jar-with-dependencies.jar"

[[services]]
  http_checks = []
  internal_port = 7070
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
